### ISSUE TITLE
Sort by PING Incorrect

### ISSUE THREAD

**Issue by gfelisberto** [andreagiavatto/Q3ServerBrowser#5]
The sort by ping does not display the correct results because it is doing a lexical sort and not a numeric sort.

I have 0 experience with Swift or Mac developing but it seems to me this is caused by `var ping: String { get }` in `Server.swift` from `GameServerQueryLibrary`.

**Comment by gfelisberto** [comment]
There are several other fields in Server and Player that could be changed to `Number` and would solve other sorting issues.

**Comment by andreagiavatto** [comment]
Thanks for your feedback @gfelisberto, i have fixed the issue with sorting by ping in the latest master/release. 
You are correct, other fields could benefit from the same change too. I am planning to update them while 'modernising' the UI and rethink/improve the UX once i have a bit more spare time later this year.
